# audit_framework.py
"""
Comprehensive SEO Audit Framework.
Each check has a stable ID, classification, and an optional 'auto_check' key
that links to a function in audit_runner.py.
"""

AUDIT_FRAMEWORK = [
# ────────────────────────────────────────
# 1. PREP
# ────────────────────────────────────────
{
    "id": "prep.analytics",
    "area": "1. Prep", "category": "Tool",
    "issue": "Analytics access",
    "tool": "Google Analytics or alt. tracking tool",
    "severity": "High", "auto_check": None,
    "problem": "No analytics access provided.",
    "preferred": "Read access to GA4 or equivalent.",
    "explanation": "Required to validate organic traffic, conversions, and traffic to broken pages.",
    "action": "Request GA4 read access from client.",
},
{
    "id": "prep.gsc",
    "area": "1. Prep", "category": "Tool",
    "issue": "Search Console access",
    "tool": "Google Search Console",
    "severity": "High", "auto_check": "gsc_connected",
    "problem": "No GSC property connected.",
    "preferred": "Domain or URL-prefix property verified.",
    "explanation": "Required for indexing, CWV field data, query data, and submitted sitemaps.",
    "action": "Request GSC access or verify ownership.",
},
{
    "id": "prep.crawl",
    "area": "1. Prep", "category": "Tool",
    "issue": "Site crawl available",
    "tool": "Lumar / Screaming Frog",
    "severity": "High", "auto_check": "crawl_loaded",
    "problem": "No fresh, complete crawl available.",
    "preferred": "Fresh crawl with DB storage + JS rendering.",
    "explanation": "Lumar and Screaming Frog have complementary reports — both ideal.",
    "action": "Run crawl with JS rendering enabled.",
},

# ────────────────────────────────────────
# 2. SECURITY
# ────────────────────────────────────────
{
    "id": "sec.errors_backlinks",
    "area": "2. Security", "category": "Public Errors",
    "issue": "Error pages with backlinks",
    "tool": "Lumar + Backlink data",
    "severity": "High", "auto_check": "errors_with_backlinks",
    "problem": "URLs with external backlinks that don't return 200/redirect.",
    "preferred": "All backlinks point to URLs that return 200.",
    "explanation": "Wasted link equity; user-experience problem.",
    "action": "Ask referrer to update link OR 301-redirect broken URL to a relevant working page.",
},
{
    "id": "sec.errors_visits",
    "area": "2. Security", "category": "Public Errors",
    "issue": "Error pages with organic visits",
    "tool": "Lumar + Analytics",
    "severity": "High", "auto_check": "errors_with_visits",
    "problem": "Broken URLs that still receive organic visits.",
    "preferred": "All URLs receiving traffic return 200.",
    "explanation": "Direct loss of revenue / leads.",
    "action": "301-redirect to closest equivalent page; investigate cause.",
},
{
    "id": "sec.errors_serp",
    "area": "2. Security", "category": "Public Errors",
    "issue": "Error pages in SERP",
    "tool": "Lumar + GSC",
    "severity": "High", "auto_check": "errors_in_serp",
    "problem": "Broken URLs still appearing in search results.",
    "preferred": "Only 200-status URLs appear in SERPs.",
    "explanation": "Causes immediate bounce; harms quality signals.",
    "action": "301-redirect or fix; request reindex once resolved.",
},
{
    "id": "sec.links_to_http",
    "area": "2. Security", "category": "URL",
    "issue": "Internal links to HTTP",
    "tool": "Lumar / Screaming Frog",
    "severity": "Medium", "auto_check": "links_to_http",
    "problem": "Internal links from HTTPS pages to HTTP pages.",
    "preferred": "All internal links use HTTPS.",
    "explanation": "Mixed-content warnings; security risk; canonicalisation confusion.",
    "action": "Update all internal links to HTTPS.",
},
{
    "id": "sec.non_https",
    "area": "2. Security", "category": "URL",
    "issue": "Non-HTTPS URLs",
    "tool": "Lumar / Screaming Frog",
    "severity": "High", "auto_check": "non_https_urls",
    "problem": "URLs served over insecure HTTP.",
    "preferred": "Entire site on HTTPS with HSTS.",
    "explanation": "Direct ranking factor; browser security warnings.",
    "action": "Migrate to HTTPS; 301 all HTTP → HTTPS; enable HSTS.",
},

# ────────────────────────────────────────
# 3. INDEXATION — Canonicals
# ────────────────────────────────────────
{
    "id": "idx.canon_non200",
    "area": "3. Indexation", "category": "Canonical",
    "issue": "Canonical to non-200",
    "tool": "Lumar", "severity": "High",
    "auto_check": "canonical_to_non_200",
    "problem": "URLs canonicalise to URLs that don't return 200.",
    "preferred": "Canonical targets always return 200.",
    "explanation": "Search engines may ignore the canonical signal entirely.",
    "action": "Update canonical to a live 200 URL or remove.",
},
{
    "id": "idx.canon_orphan",
    "area": "3. Indexation", "category": "Canonical",
    "issue": "Canonical to orphan",
    "tool": "Lumar", "severity": "Medium",
    "auto_check": "canonical_to_orphan",
    "problem": "Canonical targets a URL not linked from anywhere else.",
    "preferred": "Canonical target is internally linked.",
    "explanation": "Orphan canonicals weaken consolidation signal.",
    "action": "Add internal links to canonical target or revisit canonical strategy.",
},
{
    "id": "idx.canon_canonicalized",
    "area": "3. Indexation", "category": "Canonical",
    "issue": "Canonicalised pages",
    "tool": "Lumar", "severity": "Medium",
    "auto_check": "canonicalized_pages",
    "problem": "URL doesn't match its own canonical tag.",
    "preferred": "Intentional canonicalisation only.",
    "explanation": "Unintentional canonicalisation removes pages from index.",
    "action": "Audit each case; fix unintentional ones.",
},
{
    "id": "idx.canon_conflict",
    "area": "3. Indexation", "category": "Canonical",
    "issue": "Canonical conflicting",
    "tool": "Lumar", "severity": "High",
    "auto_check": "canonical_conflicting",
    "problem": "Multiple canonical links to different URLs.",
    "preferred": "Exactly one canonical per page.",
    "explanation": "Conflicting signals are typically ignored by Google.",
    "action": "Remove duplicates; keep only one canonical tag.",
},
{
    "id": "idx.canon_missing",
    "area": "3. Indexation", "category": "Canonical",
    "issue": "Canonical missing valid tag",
    "tool": "Lumar", "severity": "Medium",
    "auto_check": "canonical_missing",
    "problem": "URL has no canonical tag.",
    "preferred": "All public URLs have a valid canonical (self-referencing if not consolidated).",
    "explanation": "Missing canonicals leave duplicate-content decisions to Google.",
    "action": "Add self-referencing canonical or correct consolidation target.",
},
{
    "id": "idx.canon_self_ref",
    "area": "3. Indexation", "category": "Canonical",
    "issue": "Self-referencing canonical present",
    "tool": "Lumar", "severity": "Info",
    "auto_check": "canonical_self_referencing",
    "problem": "—",
    "preferred": "Non-consolidated URLs should self-reference.",
    "explanation": "Best practice for unique pages.",
    "action": "—",
},
{
    "id": "idx.canon_render_mismatch",
    "area": "3. Indexation", "category": "Canonical",
    "issue": "Rendered canonical mismatch",
    "tool": "Lumar", "severity": "High",
    "auto_check": "canonical_render_mismatch",
    "problem": "Canonical in rendered DOM differs from raw HTML.",
    "preferred": "Both match.",
    "explanation": "Indicates JS overwriting canonical — risky.",
    "action": "Server-render canonical; remove JS override.",
},
{
    "id": "idx.canon_relative",
    "area": "3. Indexation", "category": "Canonical",
    "issue": "Relative canonical URL",
    "tool": "Screaming Frog", "severity": "Medium",
    "auto_check": "canonical_relative",
    "problem": "Canonical uses relative path.",
    "preferred": "Absolute canonical URLs.",
    "explanation": "Relative canonicals can resolve incorrectly across protocols/subdomains.",
    "action": "Convert all canonicals to absolute URLs.",
},

# ────────────────────────────────────────
# 3. INDEXATION — Indexing
# ────────────────────────────────────────
{
    "id": "idx.non_indexable",
    "area": "3. Indexation", "category": "Indexing",
    "issue": "Non-indexable pages",
    "tool": "Lumar", "severity": "High",
    "auto_check": "non_indexable_pages",
    "problem": "200-status pages blocked by noindex or canonical mismatch.",
    "preferred": "Only intentionally non-indexable URLs are blocked.",
    "explanation": "Pages can't rank if non-indexable.",
    "action": "Audit noindex/canonical; remove unintended blocks.",
},
{
    "id": "idx.non_indexable_visits",
    "area": "3. Indexation", "category": "Indexing",
    "issue": "Non-indexable pages with visits",
    "tool": "Lumar + Analytics", "severity": "High",
    "auto_check": "non_indexable_with_visits",
    "problem": "Non-indexable URLs receiving organic visits.",
    "preferred": "Pages receiving traffic are indexable.",
    "explanation": "Often signals an unintended block on a valuable page.",
    "action": "Make these pages indexable.",
},

# ────────────────────────────────────────
# 3. INDEXATION — Robots.txt
# ────────────────────────────────────────
{
    "id": "idx.robots_missing",
    "area": "3. Indexation", "category": "Robots.txt",
    "issue": "Robots.txt missing",
    "tool": "Manual / Auto fetch",
    "severity": "Medium", "auto_check": "robots_txt_present",
    "problem": "/robots.txt returns 404.",
    "preferred": "Valid robots.txt at root.",
    "explanation": "Missing robots.txt means no sitemap declaration; default crawl behaviour.",
    "action": "Create a robots.txt with sitemap reference.",
},
{
    "id": "idx.robots_format",
    "area": "3. Indexation", "category": "Robots.txt",
    "issue": "Robots.txt incorrect formatting",
    "tool": "Manual / Auto parse",
    "severity": "Medium", "auto_check": "robots_txt_valid",
    "problem": "Syntax errors in robots.txt.",
    "preferred": "Valid syntax per RFC 9309.",
    "explanation": "Invalid directives may be ignored.",
    "action": "Fix syntax; test in GSC robots.txt tester.",
},
{
    "id": "idx.robots_disallowed",
    "area": "3. Indexation", "category": "Robots.txt",
    "issue": "Disallowed URLs found in crawl",
    "tool": "Lumar / Manual",
    "severity": "Medium", "auto_check": "disallowed_urls_in_crawl",
    "problem": "URLs disallowed by robots.txt are being linked internally.",
    "preferred": "Disallowed URLs should not be internally linked.",
    "explanation": "Wasted crawl signals; internal link to blocked URL is noise.",
    "action": "Remove internal links or unblock if needed.",
},

# ────────────────────────────────────────
# 3. INDEXATION — URL hygiene
# ────────────────────────────────────────
{"id": "idx.url_failed", "area": "3. Indexation", "category": "URL",
 "issue": "URL crawl failed (timeout)", "tool": "Lumar", "severity": "High",
 "auto_check": "url_failed_timeout",
 "problem": "URL didn't respond within crawler timeout.",
 "preferred": "All URLs respond < 9s.",
 "explanation": "Slow URLs are crawled less; bad UX.",
 "action": "Investigate server performance.", },
{"id": "idx.url_double_slash", "area": "3. Indexation", "category": "URL",
 "issue": "URL contains double slash", "tool": "Lumar", "severity": "Low",
 "auto_check": "url_double_slash",
 "problem": "Path contains '//'.", "preferred": "Single slashes.",
 "explanation": "Can cause duplicate-URL variants.",
 "action": "Normalise URL paths.", },
{"id": "idx.url_malformed", "area": "3. Indexation", "category": "URL",
 "issue": "Malformed URL", "tool": "Lumar", "severity": "Medium",
 "auto_check": "url_malformed",
 "problem": "Invalid URL found in links.", "preferred": "All URLs valid.",
 "explanation": "Broken links waste crawl budget and link equity.",
 "action": "Fix link source.", },
{"id": "idx.url_underscore", "area": "3. Indexation", "category": "URL",
 "issue": "URL contains underscore", "tool": "Lumar", "severity": "Low",
 "auto_check": "url_underscore",
 "problem": "Underscores in URL paths.", "preferred": "Hyphens only.",
 "explanation": "Google treats hyphens as word separators.",
 "action": "Migrate to hyphens with redirects.", },
{"id": "idx.url_capital", "area": "3. Indexation", "category": "URL",
 "issue": "URL contains capital letters", "tool": "Screaming Frog",
 "severity": "Low", "auto_check": "url_capitals",
 "problem": "Mixed case URLs.", "preferred": "Lowercase URLs.",
 "explanation": "Risk of duplicate URL variants on case-sensitive servers.",
 "action": "Normalise to lowercase + 301 redirects.", },
{"id": "idx.url_max_length", "area": "3. Indexation", "category": "URL",
 "issue": "URL exceeds max length", "tool": "Lumar", "severity": "Low",
 "auto_check": "url_too_long",
 "problem": "URLs > 115 characters.", "preferred": "Concise URLs.",
 "explanation": "Long URLs harm UX and shareability.",
 "action": "Shorten path; redirect old URLs.", },
{"id": "idx.url_params", "area": "3. Indexation", "category": "URL",
 "issue": "URL contains query parameters", "tool": "Screaming Frog",
 "severity": "Medium", "auto_check": "url_with_params",
 "problem": "Pages indexed with parameters.",
 "preferred": "Clean URLs; parameters handled via canonicals or robots.",
 "explanation": "Parameter URLs cause crawl waste and duplicates.",
 "action": "Use canonical tags or parameter handling in GSC.", },
{"id": "idx.url_non_ascii", "area": "3. Indexation", "category": "URL",
 "issue": "Non-ASCII characters in URL", "tool": "Screaming Frog",
 "severity": "Low", "auto_check": "url_non_ascii",
 "problem": "Special characters in URLs.",
 "preferred": "ASCII URLs (or punycode for IDN).",
 "explanation": "Some platforms encode characters inconsistently.",
 "action": "Normalise URLs.", },
{"id": "idx.url_trailing", "area": "3. Indexation", "category": "URL",
 "issue": "Trailing slash inconsistency", "tool": "Screaming Frog",
 "severity": "Medium", "auto_check": "url_trailing_slash_mixed",
 "problem": "Mixed trailing/non-trailing slash URLs.",
 "preferred": "Consistent policy site-wide.",
 "explanation": "Causes duplicate URL variants.",
 "action": "Pick one convention; 301 the other.", },
{"id": "idx.url_www", "area": "3. Indexation", "category": "URL",
 "issue": "WWW vs non-WWW inconsistency", "tool": "Manual",
 "severity": "High", "auto_check": "www_inconsistency",
 "problem": "Both WWW and non-WWW resolve.",
 "preferred": "One canonical hostname.",
 "explanation": "Causes duplicate-site issues.",
 "action": "301-redirect non-canonical hostname.", },

# ────────────────────────────────────────
# 3. INDEXATION — Meta Robots
# ────────────────────────────────────────
{"id": "idx.meta_nofollow", "area": "3. Indexation", "category": "Meta Robots",
 "issue": "Meta robots nofollow", "tool": "Lumar", "severity": "Medium",
 "auto_check": "meta_nofollow",
 "problem": "Pages with nofollow meta tag.",
 "preferred": "Only intentional cases.",
 "explanation": "Blocks PageRank flow on the page.",
 "action": "Audit each case.", },
{"id": "idx.meta_noindex", "area": "3. Indexation", "category": "Meta Robots",
 "issue": "Meta robots noindex", "tool": "Lumar", "severity": "High",
 "auto_check": "meta_noindex",
 "problem": "Pages prevented from indexing.",
 "preferred": "Only intentional cases.",
 "explanation": "Pages can't rank if noindexed.",
 "action": "Remove unintended noindex directives.", },

# ────────────────────────────────────────
# 3. INDEXATION — Rendering
# ────────────────────────────────────────
{"id": "idx.render_link_mismatch", "area": "3. Indexation", "category": "Rendering",
 "issue": "Rendered link count mismatch", "tool": "Lumar", "severity": "Medium",
 "auto_check": "render_link_mismatch",
 "problem": "Different link counts in DOM vs HTML.",
 "preferred": "Major links present in raw HTML.",
 "explanation": "JS-only links may not be discovered by all crawlers.",
 "action": "Server-render critical links.", },
{"id": "idx.render_word_mismatch", "area": "3. Indexation", "category": "Rendering",
 "issue": "Rendered word count mismatch", "tool": "Lumar", "severity": "High",
 "auto_check": "render_word_mismatch",
 "problem": "Major content gap between raw HTML and rendered DOM.",
 "preferred": "Critical content in raw HTML.",
 "explanation": "AI crawlers and some bots don't execute JS.",
 "action": "Move to SSR/SSG; pre-render critical content.", },
{"id": "idx.render_csr", "area": "3. Indexation", "category": "Rendering",
 "issue": "Client-side rendering", "tool": "Manual / SEO Render Insight",
 "severity": "High", "auto_check": "client_side_rendering",
 "problem": "Site relies on CSR for primary content.",
 "preferred": "SSR or SSG for SEO-critical pages.",
 "explanation": "CSR delays indexing; AI bots often skip.",
 "action": "Implement SSR/SSG.", },

# ────────────────────────────────────────
# 3. INDEXATION — XML Sitemap
# ────────────────────────────────────────
{"id": "idx.sitemap_robots", "area": "3. Indexation", "category": "XML Sitemap",
 "issue": "Sitemap declared in robots.txt", "tool": "Manual",
 "severity": "Medium", "auto_check": "sitemap_in_robots",
 "problem": "No Sitemap: directive in robots.txt.",
 "preferred": "Sitemap URL in robots.txt.",
 "explanation": "Helps all crawlers discover sitemap.",
 "action": "Add Sitemap: line to robots.txt.", },
{"id": "idx.sitemap_broken", "area": "3. Indexation", "category": "XML Sitemap",
 "issue": "Broken URLs in sitemap", "tool": "Lumar",
 "severity": "High", "auto_check": "sitemap_broken_urls",
 "problem": "Sitemap contains 4xx/5xx URLs.",
 "preferred": "All sitemap URLs return 200.",
 "explanation": "Pollutes Google's index queue.",
 "action": "Regenerate sitemap from live URLs only.", },
{"id": "idx.sitemap_missing", "area": "3. Indexation", "category": "XML Sitemap",
 "issue": "Indexable URLs missing from sitemap", "tool": "Lumar",
 "severity": "Medium", "auto_check": "sitemap_missing_urls",
 "problem": "Indexable URLs not in any sitemap.",
 "preferred": "All primary URLs in sitemap.",
 "explanation": "Slows discovery and indexing.",
 "action": "Regenerate sitemap.", },
{"id": "idx.sitemap_non_indexable", "area": "3. Indexation", "category": "XML Sitemap",
 "issue": "Non-indexable URLs in sitemap", "tool": "Lumar",
 "severity": "Medium", "auto_check": "sitemap_non_indexable",
 "problem": "Sitemap lists noindex/canonicalised URLs.",
 "preferred": "Sitemap = canonical + indexable only.",
 "explanation": "Mixed signals to Google.",
 "action": "Remove non-indexable URLs from sitemap.", },
{"id": "idx.sitemap_orphan", "area": "3. Indexation", "category": "XML Sitemap",
 "issue": "Orphan URLs in sitemap", "tool": "Lumar",
 "severity": "Medium", "auto_check": "sitemap_orphans",
 "problem": "URLs in sitemap not linked anywhere.",
 "preferred": "All sitemap URLs internally linked.",
 "explanation": "Orphans receive no PageRank.",
 "action": "Add internal links.", },
{"id": "idx.sitemap_50k", "area": "3. Indexation", "category": "XML Sitemap",
 "issue": "Sitemap > 50,000 URLs", "tool": "Lumar",
 "severity": "Medium", "auto_check": "sitemap_too_large",
 "problem": "Single sitemap exceeds 50k limit.",
 "preferred": "Split into sitemap index + child files.",
 "explanation": "Google may reject oversized sitemaps.",
 "action": "Implement sitemap index.", },
{"id": "idx.sitemap_redirect", "area": "3. Indexation", "category": "XML Sitemap",
 "issue": "Redirecting URLs in sitemap", "tool": "Lumar",
 "severity": "Medium", "auto_check": "sitemap_redirects",
 "problem": "Sitemap contains 3xx URLs.",
 "preferred": "Final destination URLs only.",
 "explanation": "Wasted crawl signals.",
 "action": "Update sitemap to final URLs.", },

# ────────────────────────────────────────
# 4. TOPIC RELEVANCE — Content
# ────────────────────────────────────────
{"id": "topic.duplicate_content", "area": "4. Topic Relevance", "category": "Content",
 "issue": "Duplicate content", "tool": "Lumar",
 "severity": "High", "auto_check": "duplicate_content",
 "problem": "Pages with similar body content.",
 "preferred": "Unique content per indexable URL.",
 "explanation": "Cannibalisation and dilution.",
 "action": "Canonicalise, consolidate, or rewrite.", },
{"id": "topic.empty_pages", "area": "4. Topic Relevance", "category": "Content",
 "issue": "Empty / thin pages", "tool": "Lumar",
 "severity": "High", "auto_check": "empty_pages",
 "problem": "Indexable URLs with negligible content.",
 "preferred": "Substantive content on indexable pages.",
 "explanation": "Thin content rarely ranks.",
 "action": "Expand, consolidate, or noindex.", },
{"id": "topic.iframes", "area": "4. Topic Relevance", "category": "Content",
 "issue": "Content in iFrames", "tool": "Screaming Frog",
 "severity": "Medium", "auto_check": "uses_iframes",
 "problem": "Critical content embedded via iframe.",
 "preferred": "Inline HTML for SEO content.",
 "explanation": "Search engines may not associate iframe content with parent.",
 "action": "Inline content; reserve iframe for media.", },

# ────────────────────────────────────────
# 4. TOPIC RELEVANCE — Headings
# ────────────────────────────────────────
{"id": "topic.h1_missing", "area": "4. Topic Relevance", "category": "H1",
 "issue": "Missing H1", "tool": "Lumar",
 "severity": "High", "auto_check": "h1_missing",
 "problem": "Indexable pages without an H1.",
 "preferred": "One unique H1 per page.",
 "explanation": "H1 is a primary topical signal.",
 "action": "Add a descriptive H1.", },
{"id": "topic.h1_duplicate", "area": "4. Topic Relevance", "category": "H1",
 "issue": "Duplicate H1", "tool": "Screaming Frog",
 "severity": "Medium", "auto_check": "h1_duplicate",
 "problem": "Same H1 across multiple URLs.",
 "preferred": "Unique H1 per page.",
 "explanation": "Reduces topical differentiation.",
 "action": "Rewrite for uniqueness.", },
{"id": "topic.h1_multiple", "area": "4. Topic Relevance", "category": "H1",
 "issue": "Multiple H1s on a page", "tool": "Lumar",
 "severity": "Medium", "auto_check": "h1_multiple",
 "problem": "Pages with > 1 H1.",
 "preferred": "Single H1 per page.",
 "explanation": "Dilutes heading hierarchy.",
 "action": "Convert duplicates to H2/H3.", },

# ────────────────────────────────────────
# 4. TOPIC RELEVANCE — Hreflang
# ────────────────────────────────────────
{"id": "topic.hreflang_broken", "area": "4. Topic Relevance", "category": "Hreflang",
 "issue": "Broken hreflang", "tool": "Lumar",
 "severity": "High", "auto_check": "hreflang_broken",
 "problem": "Hreflang URL returns non-200.",
 "preferred": "All hreflang targets return 200.",
 "explanation": "Broken hreflang signals are ignored.",
 "action": "Update hreflang to live URLs.", },
{"id": "topic.hreflang_missing_back", "area": "4. Topic Relevance", "category": "Hreflang",
 "issue": "Missing back-reference", "tool": "Lumar",
 "severity": "High", "auto_check": "hreflang_missing_back",
 "problem": "Reciprocal hreflang missing.",
 "preferred": "All hreflangs reciprocal.",
 "explanation": "Google ignores non-reciprocal hreflang.",
 "action": "Implement bi-directional hreflang.", },
{"id": "topic.hreflang_invalid", "area": "4. Topic Relevance", "category": "Hreflang",
 "issue": "Invalid hreflang attribute", "tool": "Lumar",
 "severity": "High", "auto_check": "hreflang_invalid_code",
 "problem": "Non-ISO language/country codes.",
 "preferred": "Valid ISO 639-1 / 3166-1.",
 "explanation": "Invalid codes are ignored.",
 "action": "Replace with valid codes.", },

# ────────────────────────────────────────
# 4. TOPIC RELEVANCE — Images
# ────────────────────────────────────────
{"id": "topic.img_alt", "area": "4. Topic Relevance", "category": "Images",
 "issue": "Images missing alt", "tool": "Screaming Frog",
 "severity": "Medium", "auto_check": "img_missing_alt",
 "problem": "<img> without alt attribute.",
 "preferred": "Descriptive alt on content images; alt='' on decorative.",
 "explanation": "Accessibility + image SEO.",
 "action": "Add alt text to all content images.", },
{"id": "topic.img_dimensions", "area": "4. Topic Relevance", "category": "Images",
 "issue": "Image dimensions not set", "tool": "Screaming Frog",
 "severity": "Medium", "auto_check": "img_no_dimensions",
 "problem": "<img> without width/height.",
 "preferred": "Width and height defined.",
 "explanation": "Improves CLS.",
 "action": "Add width/height attributes.", },
{"id": "topic.img_broken", "area": "4. Topic Relevance", "category": "Images",
 "issue": "Broken images", "tool": "Screaming Frog",
 "severity": "Medium", "auto_check": "img_broken",
 "problem": "Image URLs return non-200.",
 "preferred": "All images load.",
 "explanation": "Bad UX.",
 "action": "Fix paths or remove references.", },
{"id": "topic.img_redirect", "area": "4. Topic Relevance", "category": "Images",
 "issue": "Redirecting images", "tool": "Screaming Frog",
 "severity": "Low", "auto_check": "img_redirects",
 "problem": "Image URLs redirect.",
 "preferred": "Direct 200 image URLs.",
 "explanation": "Slows page load.",
 "action": "Update src to final URL.", },
{"id": "topic.img_size", "area": "4. Topic Relevance", "category": "Images",
 "issue": "Oversized images", "tool": "Screaming Frog",
 "severity": "Medium", "auto_check": "img_too_large",
 "problem": "Images > 100KB without modern formats.",
 "preferred": "WebP/AVIF; appropriately sized.",
 "explanation": "Hurts LCP.",
 "action": "Convert and compress.", },

# ────────────────────────────────────────
# 4. TOPIC RELEVANCE — Internal Links
# ────────────────────────────────────────
{"id": "topic.internal_broken", "area": "4. Topic Relevance", "category": "Internal links",
 "issue": "Broken internal links", "tool": "Lumar",
 "severity": "High", "auto_check": "internal_broken",
 "problem": "Internal links to 4xx/5xx URLs.",
 "preferred": "All internal links return 200.",
 "explanation": "Wasted PageRank; bad UX.",
 "action": "Fix or remove broken links.", },
{"id": "topic.internal_redirect", "area": "4. Topic Relevance", "category": "Internal links",
 "issue": "Internal links to redirects", "tool": "Lumar",
 "severity": "Medium", "auto_check": "internal_to_redirect",
 "problem": "Internal links pointing to 3xx URLs.",
 "preferred": "Direct links to final URLs.",
 "explanation": "Diluted PageRank; slower UX.",
 "action": "Update to final destination URLs.", },
{"id": "topic.anchor_generic", "area": "4. Topic Relevance", "category": "Internal links",
 "issue": "Generic anchor text", "tool": "Manual / Crawler",
 "severity": "Low", "auto_check": "anchor_generic",
 "problem": "Anchors like 'click here', 'read more'.",
 "preferred": "Descriptive anchors.",
 "explanation": "Anchor text is a relevance signal.",
 "action": "Rewrite anchors with topical keywords.", },

# ────────────────────────────────────────
# 4. TOPIC RELEVANCE — Markup
# ────────────────────────────────────────
{"id": "topic.schema_missing", "area": "4. Topic Relevance", "category": "Markup",
 "issue": "Structured data missing", "tool": "Lumar",
 "severity": "Medium", "auto_check": "schema_missing",
 "problem": "Pages without any schema markup.",
 "preferred": "Relevant schema (Article, Product, FAQ, Organization).",
 "explanation": "Enables rich results; AI search citations.",
 "action": "Implement JSON-LD schema.", },
{"id": "topic.schema_errors", "area": "4. Topic Relevance", "category": "Markup",
 "issue": "Structured data errors", "tool": "Rich Results Test",
 "severity": "Medium", "auto_check": "schema_errors",
 "problem": "Invalid schema syntax.",
 "preferred": "Validates in Rich Results Test.",
 "explanation": "Invalid schema is ignored.",
 "action": "Validate and fix.", },
{"id": "topic.og_missing", "area": "4. Topic Relevance", "category": "Markup",
 "issue": "Missing Open Graph / Twitter Card", "tool": "Lumar",
 "severity": "Low", "auto_check": "og_missing",
 "problem": "Pages without OG/Twitter tags.",
 "preferred": "OG title, description, image set.",
 "explanation": "Affects social CTR.",
 "action": "Add OG tags.", },

# ────────────────────────────────────────
# 4. TOPIC RELEVANCE — Meta Description
# ────────────────────────────────────────
{"id": "topic.md_missing", "area": "4. Topic Relevance", "category": "Meta Description",
 "issue": "Missing meta description", "tool": "Lumar",
 "severity": "Medium", "auto_check": "md_missing",
 "problem": "Indexable pages without description.",
 "preferred": "Unique 50–230 char description.",
 "explanation": "Affects SERP CTR.",
 "action": "Write unique descriptions.", },
{"id": "topic.md_duplicate", "area": "4. Topic Relevance", "category": "Meta Description",
 "issue": "Duplicate meta description", "tool": "Lumar",
 "severity": "Low", "auto_check": "md_duplicate",
 "problem": "Same description across URLs.",
 "preferred": "Unique per page.",
 "explanation": "Misses targeting opportunities.",
 "action": "Rewrite for uniqueness.", },
{"id": "topic.md_too_short", "area": "4. Topic Relevance", "category": "Meta Description",
 "issue": "Meta description too short", "tool": "Lumar",
 "severity": "Low", "auto_check": "md_too_short",
 "problem": "< 50 characters.",
 "preferred": "50–230 characters.",
 "explanation": "Underutilises SERP space.",
 "action": "Expand.", },
{"id": "topic.md_too_long", "area": "4. Topic Relevance", "category": "Meta Description",
 "issue": "Meta description too long", "tool": "Lumar",
 "severity": "Low", "auto_check": "md_too_long",
 "problem": "> 230 characters.",
 "preferred": "50–230 characters.",
 "explanation": "Truncated in SERPs.",
 "action": "Trim.", },

# ────────────────────────────────────────
# 4. TOPIC RELEVANCE — Meta Title
# ────────────────────────────────────────
{"id": "topic.title_missing", "area": "4. Topic Relevance", "category": "Meta Title",
 "issue": "Missing title", "tool": "Lumar",
 "severity": "High", "auto_check": "title_missing",
 "problem": "Indexable URLs with blank titles.",
 "preferred": "Unique 50–60 char title.",
 "explanation": "Top on-page ranking factor.",
 "action": "Add unique titles.", },
{"id": "topic.title_duplicate", "area": "4. Topic Relevance", "category": "Meta Title",
 "issue": "Duplicate title", "tool": "Lumar",
 "severity": "High", "auto_check": "title_duplicate",
 "problem": "Same title across URLs.",
 "preferred": "Unique titles.",
 "explanation": "Confuses ranking.",
 "action": "Rewrite for uniqueness.", },
{"id": "topic.title_too_short", "area": "4. Topic Relevance", "category": "Meta Title",
 "issue": "Title too short", "tool": "Lumar",
 "severity": "Low", "auto_check": "title_too_short",
 "problem": "< 30 characters.",
 "preferred": "30–60 characters.",
 "explanation": "Misses keyword opportunities.",
 "action": "Expand.", },
{"id": "topic.title_too_long", "area": "4. Topic Relevance", "category": "Meta Title",
 "issue": "Title too long", "tool": "Lumar",
 "severity": "Medium", "auto_check": "title_too_long",
 "problem": "> 60 characters / 600 px.",
 "preferred": "30–60 characters.",
 "explanation": "Truncated in SERPs.",
 "action": "Trim.", },

# ────────────────────────────────────────
# 4. TOPIC RELEVANCE — Orphans
# ────────────────────────────────────────
{"id": "topic.orphan", "area": "4. Topic Relevance", "category": "Orphaned pages",
 "issue": "Orphan pages", "tool": "Lumar",
 "severity": "Medium", "auto_check": "orphans",
 "problem": "Indexable pages with no internal links.",
 "preferred": "All indexable pages internally linked.",
 "explanation": "Orphans receive no PageRank.",
 "action": "Add internal links.", },
{"id": "topic.orphan_backlinks", "area": "4. Topic Relevance", "category": "Orphaned pages",
 "issue": "Orphans with backlinks", "tool": "Lumar + backlinks",
 "severity": "High", "auto_check": "orphans_backlinks",
 "problem": "Orphan pages with external backlinks.",
 "preferred": "Internally link to consolidate equity.",
 "explanation": "Wasted external link equity.",
 "action": "Link to high-value orphans from relevant pages.", },

# ────────────────────────────────────────
# 5. AUTHORITY & TRUST
# ────────────────────────────────────────
{"id": "auth.broken_css", "area": "5. Authority & Trust", "category": "Broken",
 "issue": "Broken CSS", "tool": "Lumar",
 "severity": "Medium", "auto_check": "broken_css",
 "problem": "CSS file returns non-200.",
 "preferred": "All CSS returns 200.",
 "explanation": "Breaks rendering.",
 "action": "Fix paths.", },
{"id": "auth.broken_js", "area": "5. Authority & Trust", "category": "Broken",
 "issue": "Broken JS", "tool": "Lumar",
 "severity": "Medium", "auto_check": "broken_js",
 "problem": "JS file returns non-200.",
 "preferred": "All JS returns 200.",
 "explanation": "Breaks functionality and rendering.",
 "action": "Fix paths.", },
{"id": "auth.cwv_lcp", "area": "5. Authority & Trust", "category": "Core Web Vitals",
 "issue": "Largest Contentful Paint (LCP)", "tool": "PSI / GSC",
 "severity": "High", "auto_check": "cwv_lcp",
 "problem": "LCP > 2.5s.",
 "preferred": "≤ 2.5s good.",
 "explanation": "Direct ranking factor (mobile + desktop).",
 "action": "Optimise hero image, server response, render-blocking JS.", },
{"id": "auth.cwv_inp", "area": "5. Authority & Trust", "category": "Core Web Vitals",
 "issue": "Interaction to Next Paint (INP)", "tool": "PSI / GSC",
 "severity": "High", "auto_check": "cwv_inp",
 "problem": "INP > 200ms.",
 "preferred": "≤ 200ms good.",
 "explanation": "Replaced FID March 2024; ranking factor.",
 "action": "Reduce JS execution time; defer non-critical scripts.", },
{"id": "auth.cwv_cls", "area": "5. Authority & Trust", "category": "Core Web Vitals",
 "issue": "Cumulative Layout Shift (CLS)", "tool": "PSI / GSC",
 "severity": "High", "auto_check": "cwv_cls",
 "problem": "CLS > 0.1.",
 "preferred": "≤ 0.1 good.",
 "explanation": "Layout shifts hurt UX and rankings.",
 "action": "Set image dimensions; reserve space for ads/embeds.", },
{"id": "auth.ttfb", "area": "5. Authority & Trust", "category": "Page Speed",
 "issue": "Time To First Byte", "tool": "PSI",
 "severity": "Medium", "auto_check": "ttfb",
 "problem": "TTFB > 800ms.",
 "preferred": "< 800ms.",
 "explanation": "Slow server response cascades into LCP.",
 "action": "Optimise hosting, caching, DB.", },
{"id": "auth.html_size", "area": "5. Authority & Trust", "category": "Page Speed",
 "issue": "Excessive HTML size", "tool": "Lumar",
 "severity": "Low", "auto_check": "html_size",
 "problem": "HTML > 100KB.",
 "preferred": "< 100KB.",
 "explanation": "Inflates LCP and crawl cost.",
 "action": "Trim inline content; lazy-load.", },
{"id": "auth.lazy", "area": "5. Authority & Trust", "category": "Page Speed",
 "issue": "Lazy-loading utilised", "tool": "Manual",
 "severity": "Low", "auto_check": "lazy_loading",
 "problem": "No lazy-loading on below-fold images.",
 "preferred": "loading='lazy' below the fold.",
 "explanation": "Saves bandwidth.",
 "action": "Add loading='lazy' attribute.", },
{"id": "auth.mobile", "area": "5. Authority & Trust", "category": "Public Errors",
 "issue": "Not mobile-friendly", "tool": "PSI",
 "severity": "High", "auto_check": "mobile_friendly",
 "problem": "Page fails mobile-friendly test.",
 "preferred": "Pass mobile-friendly.",
 "explanation": "Mobile-first indexing.",
 "action": "Use responsive design.", },
{"id": "auth.redirect_chains", "area": "5. Authority & Trust", "category": "Redirect",
 "issue": "Redirect chains", "tool": "Lumar",
 "severity": "Medium", "auto_check": "redirect_chains",
 "problem": "Multiple hops in redirects.",
 "preferred": "Single 301 hop.",
 "explanation": "Diluted equity; slower UX.",
 "action": "Update to direct redirects.", },
{"id": "auth.redirect_loops", "area": "5. Authority & Trust", "category": "Redirect",
 "issue": "Redirect loops", "tool": "Lumar",
 "severity": "High", "auto_check": "redirect_loops",
 "problem": "Infinite redirect loops.",
 "preferred": "No loops.",
 "explanation": "Pages inaccessible.",
 "action": "Break the loop.", },
{"id": "auth.redirect_non301", "area": "5. Authority & Trust", "category": "Redirect",
 "issue": "Non-301 redirects", "tool": "Lumar",
 "severity": "Medium", "auto_check": "redirect_non_301",
 "problem": "302/meta refresh redirects for permanent moves.",
 "preferred": "301 for permanent.",
 "explanation": "302s pass less equity.",
 "action": "Convert to 301.", },
{"id": "auth.4xx", "area": "5. Authority & Trust", "category": "Server Responses",
 "issue": "4XX errors", "tool": "Lumar",
 "severity": "High", "auto_check": "errors_4xx",
 "problem": "Pages returning 400/404/410.",
 "preferred": "No internal 4xx.",
 "explanation": "Wasted crawl; bad UX.",
 "action": "Fix or 301-redirect.", },
{"id": "auth.5xx", "area": "5. Authority & Trust", "category": "Server Responses",
 "issue": "5XX errors", "tool": "Lumar",
 "severity": "High", "auto_check": "errors_5xx",
 "problem": "Server-side errors.",
 "preferred": "No 5xx.",
 "explanation": "Blocks indexing.",
 "action": "Investigate server.", },
{"id": "auth.soft_404", "area": "5. Authority & Trust", "category": "Server Responses",
 "issue": "Soft 404s", "tool": "GSC",
 "severity": "Medium", "auto_check": "soft_404",
 "problem": "200 status but 'not found' content.",
 "preferred": "Return real 404.",
 "explanation": "Wastes crawl budget.",
 "action": "Return correct 404 status.", },
]


]


# ─────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────

def by_area():
   """Return dict {area: [checks...]}."""
   out = {}
   for c in AUDIT_FRAMEWORK:
       out.setdefault(c["area"], []).append(c)
   return out


def by_id(check_id: str):
   """Return the check dict matching this id, or None."""
   return next((c for c in AUDIT_FRAMEWORK if c["id"] == check_id), None)


SEVERITY_ORDER = {"High": 0, "Medium": 1, "Low": 2, "Info": 3}
